### ISSUE TITLE
Marker and Menu not Display

### ISSUE THREAD

**Issue by DioneB** [TanguyOrtegat/esx_jb_dj#2]
Hi JagerB, First of all I would like to thank and congratulate you for the work done and for sharing!

 but when I activate the script, nothing happens. no marker appears and no menu appears, in the Client Console and Server Console does not show any error, without displaying the error in the console I can not figure out the problem, so I'm opening an Issue

-FT Libs (Installed & Active & Loading before esx_jb_dj)

**Comment by kevintransp** [comment]
Maybe we need to set the job to use the dj booth. I'm having the same issue. In the readme there is a mention about setting to the job you want, but how/where?

**Comment by DioneB** [comment]
well, I checked the code and there is no job check, but there is the event:
esx_jb_dj: enabledjbooth
I believe it should come by default disabled, and you should activate remotely by calling the event: "esx_jb_dj: enabledjbooth"
I'm at work, later when I return, I'll test if that's what I mentioned.

**Comment by kevintransp** [comment]
That would be great, in my case i want the unicorn job to be able to acces the dj booth.

**Comment by kevintransp** [comment]
Why clossed, jou have a solution?
