### ISSUE TITLE
how to disable the default GTA5 music

### ISSUE THREAD

**Issue by cantera123** [TanguyOrtegat/esx_jb_dj#3]
how to disable the default GTA5 music in the galaxy club? I can hear it in the background

**Comment by TanguyOrtegat** [comment]
idk, never tested it out, you should maybe ask on fivem forum, and if you have the answer, post it here too :)

**Comment by BadCodesGG** [comment]
```
// removes audio from vanilla unicorn
SetStaticEmitterEnabled('LOS_SANTOS_VANILLA_UNICORN_01_STAGE', false)
SetStaticEmitterEnabled('LOS_SANTOS_VANILLA_UNICORN_02_MAIN_ROOM', false)
SetStaticEmitterEnabled('LOS_SANTOS_VANILLA_UNICORN_03_BACK_ROOM', false)
```

**Comment by TanguyOrtegat** [comment]
> ```
> // removes audio from vanilla unicorn
> SetStaticEmitterEnabled('LOS_SANTOS_VANILLA_UNICORN_01_STAGE', false)
> SetStaticEmitterEnabled('LOS_SANTOS_VANILLA_UNICORN_02_MAIN_ROOM', false)
> SetStaticEmitterEnabled('LOS_SANTOS_VANILLA_UNICORN_03_BACK_ROOM', false)
> ```

oh great thanks ! I assume that you need to put those natives in a while loop ?
