### ISSUE TITLE
cant start this script

### ISSUE THREAD

**Issue by kFxDaKing** [TanguyOrtegat/esx_jb_dj#4]
When i start this script in game, in f8 start esx_jb_dj my game complete freeze and stop working.

When i type start esx_jb_dj in server.cfg my game stuck in loading screen.

I have ft_libs.

**Comment by TanguyOrtegat** [comment]
could you send me client / server logs ? thanks. Should work normally like any one else ...

**Comment by kFxDaKing** [comment]
There isnt any error about it..
F8 console is clean
Server console same..

When esx_jb_dj is started, my game stuck in loading screen on "Awaiting scripts" and my whole computer stucks, i have ho restart pc.

When i stop esx_jb_dj it loads without any problem :/

**Comment by kFxDaKing** [comment]
I could share screen or something if you add me on discord
kFxDaKing#7380

**Comment by TanguyOrtegat** [comment]
fixed
